### ISSUE TITLE
Plugin works for index_... documents

### ISSUE THREAD

**Issue by alexzaporozhets** [doup/metalsmith-multi-language#1]
It won't creates file for:
- src/mission_fr.html
- src/clients/intro_fr.html
- src/clients/subfolder/intro_fr.html

**Comment by doup** [comment]
Can you elaborate on the issue?

**Comment by alexzaporozhets** [comment]
The problem is that your plugin does not create files located inside directories or don't contains "index" in the name

![build_js_-_website-metalsmith_-____webstormprojects_website-metalsmith_](https://cloud.githubusercontent.com/assets/891472/9111794/1a5ca162-3c53-11e5-8a42-eb6bae2f3163.png)

![build_js_-_website-metalsmith_-____webstormprojects_website-metalsmith_](https://cloud.githubusercontent.com/assets/891472/9111853/5d817ad0-3c53-11e5-9c7b-528ee02b1e3a.png)

**Comment by doup** [comment]
The plugin does not change the files path, that it's only done for the _index_ files. Try using something like [metalsmith-permalinks](https://github.com/segmentio/metalsmith-permalinks) for handling the urls, e.g.:

``` js
.use(branch('articles/*')
    .use(permalinks({
        pattern: ':locale/:title'
    }))
)
```

By the way, it seems also that `mission.html` should be `mission_en.html`.

**Comment by alexzaporozhets** [comment]
It seems as unexpected behaviour at least for me and my colleagues. We used docpad and https://github.com/kizu/docpad-plugin-multilang

**Comment by mattbanks** [comment]
@doup I wonder if you could clarify the use of `branch` in your example using metalsmith-permalinks? My folder structure is

```
- src
  - section 1
    - area 1
      - index_en_us.json
      - index_es_es.json
    - area 2
      - index_en_us.json
      - index_es_es.json
  - section 2
    - area 1
      - index_en_us.json
      - index_es_es.json
    - area 2
      - index_en_us.json
      - index_es_es.json
  - section 3
    - index_en_us.json
    - index_es_es.json
```

Trying to use your plugin to get proper translations for everything, but having trouble getting the proper permalink setup working to have it go through all sub-folders. Any thoughts?

_(didn't want to open a new issue since this one existed already)_

**Comment by denizdogan** [comment]
@mattbanks The `branch` call is most likely from [metalsmith-branch](https://www.npmjs.com/package/metalsmith-branch) which lets you run separate pipelines on specific targets.
